ns="Base"
package="Inigo"
version="0.0.1"

description="Inigo Package Manager"
modules=["Client.Client"]
depends=["idris2", "base", "contrib", "prelude", "lib", "idrall"]
main="Client.Client"
executable="inigo"

[deps]
Base.Color="^0.0.1"
Base.Extra="^0.0.3"
Base.Fmt="^0.0.1"
Base.Markdown="^0.0.4"
Base.SemVar="^0.0.1"
Base.Toml="^0.0.1"

[dev-deps]
Base.IdrTest="^0.0.1" # Note: Dev dependency

[[extra-dep]]
download="git"
commit="d96c1240d0415208b1d32e7ae0930eb63c69d9d7"
url="https://github.com/alexhumphreys/idrall.git"
sub-folders=[""]
